// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double bigger = 0.0;
		double smaller = 0.0;
		for(int i=0; i<n;i++){
			double num = Math.random();
			if (num>0.5){
				bigger++;
			}else{
				smaller++;
			}
		}
		double ratio=0.0;
		if(smaller==0){
			System.out.println("==0,cannot divide by 0");
		}else{
			ratio = bigger/smaller;	
		}
		
		System.out.println("> 0.5:  "+(int)bigger+" times");
		System.out.println("<= 0.5:  "+(int)smaller+" times");
		System.out.println("Ratio:  "+ratio);
		
	}
}
